# Generated by Django 3.1.4 on 2021-01-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAsString', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.CharField(blank=True, max_length=200, null=True)),
                ('interval', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=400, null=True)),
                ('checked', models.IntegerField(blank=True, default=0, null=True)),
                ('streak', models.IntegerField(blank=True, default=0, null=True)),
                ('longestStreak', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateAsString', models.CharField(blank=True, max_length=200, null=True)),
                ('checkedList', models.ManyToManyField(to='crm.Repeats')),
            ],
        ),
    ]
