# Generated by Django 3.1.4 on 2020-12-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='crm.Tag'),
        ),
    ]
