# Generated by Django 3.1.4 on 2020-12-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_order_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='interval',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='minutes',
            field=models.FloatField(null=True),
        ),
    ]
