# Generated by Django 3.1.4 on 2020-12-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20201230_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='order',
            name='timeItWillTake',
        ),
    ]
