# Generated by Django 3.1.4 on 2020-12-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20201230_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeItWillTake',
            field=models.IntegerField(null=True),
        ),
    ]
