# Generated by Django 3.1.4 on 2020-12-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20201230_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='predefinedHabit',
            field=models.CharField(choices=[('Call Mum', 'Call Mum'), ('Workout', 'Workout'), ('Buy Groceries', 'Buy Groceries'), ('Study Maths', 'Study Maths'), ('Meditate', 'Meditate')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='habit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
