# Generated by Django 3.1.4 on 2020-12-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20201230_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='habit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='predefinedHabit',
            field=models.CharField(blank=True, choices=[('Call Mum', 'Call Mum'), ('Workout', 'Workout'), ('Buy Groceries', 'Buy Groceries'), ('Study Maths', 'Study Maths'), ('Meditate', 'Meditate')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeItWillTake',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
