# Generated by Django 3.1.4 on 2020-12-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20201230_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timeItWillTake',
        ),
    ]
