# Generated by Django 3.1.4 on 2020-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_order_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checked',
            field=models.IntegerField(),
        ),
    ]
