# Generated by Django 3.1.4 on 2020-12-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20201230_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
