# Generated by Django 3.1.4 on 2020-12-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20201230_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='checked',
        ),
        migrations.AddField(
            model_name='order',
            name='counts',
            field=models.ManyToManyField(to='crm.Count'),
        ),
    ]
