# Generated by Django 3.1.4 on 2020-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20201230_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='counts',
        ),
        migrations.AddField(
            model_name='order',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
