# Generated by Django 3.1.4 on 2020-12-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20201231_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.ManyToManyField(to='crm.Count'),
        ),
        migrations.AlterField(
            model_name='count',
            name='checked',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
