# Generated by Django 3.1.4 on 2020-12-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20201231_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.AlterField(
            model_name='count',
            name='checked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.order'),
        ),
    ]
