# Generated by Django 3.1.4 on 2020-12-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20201231_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='checked',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.order'),
        ),
    ]
