# Generated by Django 3.1.4 on 2020-12-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20201231_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checked',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
