# Generated by Django 3.1.4 on 2020-12-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20201231_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strike',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='checked',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
