# Generated by Django 3.1.4 on 2021-01-02 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20201231_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
