# Generated by Django 3.1.4 on 2021-01-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_count_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
