# Generated by Django 3.1.4 on 2021-01-02 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20210101_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='count',
            name='time_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='count',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
