# Generated by Django 3.1.4 on 2021-01-02 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_remove_count_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
