# Generated by Django 3.1.4 on 2021-01-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_count_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='count',
            name='updated_on',
        ),
    ]
