# Generated by Django 3.1.4 on 2021-01-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_auto_20210101_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
