# Generated by Django 3.1.4 on 2021-01-02 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_auto_20210101_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='timeStamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
