# Generated by Django 3.1.4 on 2021-01-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_count_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
