# Generated by Django 3.1.4 on 2021-01-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checked',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
