# Generated by Django 3.1.4 on 2021-01-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_auto_20210101_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
