# Generated by Django 3.1.4 on 2021-01-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_auto_20210101_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='strike',
        ),
    ]
