# Generated by Django 3.1.4 on 2021-01-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_remove_order_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strike',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
