# Generated by Django 3.1.4 on 2021-01-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_order_strike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ManyToManyField(to='crm.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
