# Generated by Django 3.1.4 on 2021-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_auto_20210102_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='checked',
        ),
        migrations.AddField(
            model_name='count',
            name='strikeCount',
            field=models.ManyToManyField(to='crm.Order'),
        ),
    ]
