# Generated by Django 3.1.4 on 2021-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_auto_20210102_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeats',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
