# Generated by Django 3.1.4 on 2021-01-03 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_auto_20210102_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeats',
            name='timeStamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
