# Generated by Django 3.1.4 on 2021-01-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_repeats_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='strikeCount',
            new_name='order',
        ),
    ]
