# Generated by Django 3.1.4 on 2021-01-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_auto_20210103_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkedList',
        ),
        migrations.RemoveField(
            model_name='order',
            name='strikeList',
        ),
    ]
