# Generated by Django 3.1.4 on 2021-01-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_auto_20210103_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkedList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.repeats'),
        ),
        migrations.AddField(
            model_name='order',
            name='strikeList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.count'),
        ),
    ]
