# Generated by Django 3.1.4 on 2021-01-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_auto_20210103_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
