# Generated by Django 3.1.4 on 2021-01-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_auto_20210103_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkedList',
        ),
        migrations.AddField(
            model_name='order',
            name='checkedList',
            field=models.ManyToManyField(to='crm.Repeats'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='strikeList',
        ),
        migrations.AddField(
            model_name='order',
            name='strikeList',
            field=models.ManyToManyField(to='crm.Count'),
        ),
    ]
