# Generated by Django 3.1.4 on 2021-01-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_auto_20210103_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeats',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='strike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
