# Generated by Django 3.1.4 on 2021-01-04 00:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_auto_20210103_1456'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='repeats',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
