# Generated by Django 3.1.4 on 2021-01-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_auto_20210103_1644'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='repeats',
            managers=[
            ],
        ),
    ]
