# Generated by Django 3.1.4 on 2021-01-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_auto_20210103_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
