# Generated by Django 3.1.4 on 2021-01-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_count_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='interval',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=400, null=True),
        ),
    ]
