# Generated by Django 3.1.4 on 2021-01-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_auto_20210104_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
