# Generated by Django 3.1.4 on 2021-01-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_auto_20210105_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
