# Generated by Django 3.1.4 on 2021-01-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_order_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='test',
            new_name='dateAsString',
        ),
        migrations.RenameField(
            model_name='repeats',
            old_name='test',
            new_name='dateAsString',
        ),
    ]
