# Generated by Django 3.1.4 on 2021-01-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_auto_20210109_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeats',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='repeats',
            name='timeStamp',
        ),
    ]
