# Generated by Django 3.1.4 on 2021-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_auto_20210109_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='longestStreak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
